### ISSUE TITLE
POST endpoint of 'js-my-first-app' does not work.

### ISSUE THREAD

**Issue by mryhryki** [klothoplatform/sample-apps#68]
I tried to run Klotho with [Getting Started](https://klo.dev/docs/tutorials/your_first_klotho_app#repository), and found an error in sample app.

Requesting `POST http://localhost:3000/pets` and responds error by `ReferenceError: owner is not defined`.

```shell
# Setup
git clone https://github.com/KlothoPlatform/sample-apps.git
cd sample-apps/js-my-first-app
npm install
```

```shell
# Server
node index.js
```

```shell
# HTTP Request
$ curl http://localhost:3000/pets
{}

$ curl -XPOST http://localhost:3000/pets
{"error":{}} # <= Here
```

Changes to output error content. 

```diff
diff --git a/js-my-first-app/index.js b/js-my-first-app/index.js
index 48ebe74..7802183 100644
--- a/js-my-first-app/index.js
+++ b/js-my-first-app/index.js
@@ -14,6 +14,7 @@ async function addPetName(req, res) {
     await petsByOwner.set(owner, pet);
     res.send(`Added ${pet} as ${owner}'s pet`)
   } catch (error) {
+    console.error(error)
     res.status(500).send({error})
   }
 }
```

Error message:

```
ReferenceError: owner is not defined
    at addPetName (/Users/mryhryki/temp/sample-apps/js-my-first-app/index.js:14:27)
    at Layer.handle [as handle_request] (/Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/express/lib/router/index.js:346:12)
    at next (/Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/express/lib/router/index.js:280:10)
    at jsonParser (/Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/body-parser/lib/types/json.js:110:7)
    at Layer.handle [as handle_request] (/Users/mryhryki/temp/sample-apps/js-my-first-app/node_modules/express/lib/router/layer.js:95:5)
```

Error occured by:

https://github.com/klothoplatform/sample-apps/blob/7868d1590a32326f7abfa9cbff7b9295ec122ab6/js-my-first-app/index.js#L14

But I don't know Klotho, so I dont know how to fix it.

**Comment by DavidSeptimus-Klotho** [comment]
@mryhryki thanks for raising this issue. The `addPetName` function seems to be missing a line of code to extract the `pet` and `owner` values from the request body. We'll make sure to commit this fix.

```typescript
async function addPetName(req, res) {
  const {pet, owner} = req.body; // <-- this line was missing
  try {
    await petsByOwner.set(owner, pet);
    res.send(`Added ${pet} as ${owner}'s pet`);
  } catch (error) {
    res.status(500).json({message: error.message});
  }
}
```
